project_id: '624298'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: 1
files:
  - source: '*en_US.po'
    ignore_settings: 1
    translation: /%original_path%/%locale_with_underscore%.%file_extension%
